### ISSUE TITLE
(render-cleanup) Map State Crash

### ISSUE THREAD

**Issue by turtlewit** [turtlewit/GSHS_RPG#13]
The game will crash if, at any point, the game attempts to switch to the 'Map' state. 

```
Northernmost Walkway Tile
You are standing on a white tiled walkway, surrounded by void. Every object
Traceback (most recent call last):om every angle, creating a distinctly
  File "H:\Game Development\python\lib\site-packages\cx_Freeze\initscripts\Conso
le.py", line 27, in <module>
    exec(code, m.__dict__)
  File "Source Files\GSHS_RPG\main.py", line 35, in <module>
  File "Source Files\GSHS_RPG\main.py", line 31, in __init__
  File "Source Files\GSHS_RPG\AdventureEngine\CoreEngine\engine.py", line 40, in
 Start
  File "Source Files\GSHS_RPG\AdventureEngine\CoreEngine\engine.py", line 56, in
 Run
  File "Source Files\GSHS_RPG\AdventureEngine\CoreEngine\game.py", line 30, in U
pdate
  File "Source Files\GSHS_RPG\AdventureEngine\CoreEngine\gameobject.py", line 51
, in UpdateAll
  File "Source Files\GSHS_RPG\AdventureEngine\CoreEngine\gameobject.py", line 48
, in UpdateAll
  File "Source Files\GSHS_RPG\AdventureEngine\CoreEngine\gameobject.py", line 45
, in Update
  File "Source Files\GSHS_RPG\src\player.py", line 157, in Update
AttributeError: 'MapState' object has no attribute 'AddText'

H:\Game Development\Builds\GSHS_RPG6542838>
>map
```

Possible fix is to add a check, in player, to know when the state is exploration state.

**Comment by turtlewit** [comment]
Fixed in commit f79f9da.
