### ISSUE TITLE
Bug Report Numbero Juan

### ISSUE THREAD

**Issue by Fivogyh** [turtlewit/GSHS_RPG#8]
First Bug found 12/13:
 Typing "Inspect" will crash game, possibly typing more.

```
Northernmost Walkway Tile
You are standing on a white tiled walkway, surrounded by void. Every object
Traceback (most recent call last):om every angle, creating a distinctly
  File "\\gshs-dc\gshs\shared\Game Development\Python\lib\site-packages\cx_Freez
e\initscripts\Console.py", line 27, in <module>meter to the north. There are
    exec(code, m.__dict__)the path every few meters.
  File "GSHS_RPG\main.py", line 17, in <module>here.
  File "GSHS_RPG\main.py", line 13, in __init__
  File "GSHS_RPG\AdventureEngine\CoreEngine\engine.py", line 22, in Start
  File "GSHS_RPG\AdventureEngine\CoreEngine\engine.py", line 38, in Run
  File "GSHS_RPG\AdventureEngine\CoreEngine\game.py", line 12, in Update
  File "GSHS_RPG\AdventureEngine\CoreEngine\gameobject.py", line 30, in UpdateAl
l
  File "GSHS_RPG\AdventureEngine\CoreEngine\gameobject.py", line 27, in Update
  File "GSHS_RPG\AdventureEngine\components\state.py", line 19, in Update
  File "GSHS_RPG\src\states.py", line 153, in Update2
IndexError: list index out of range

H:\Game Development\Builds\GSHS_RPG_Alpha>





>inspect
```
(>meme arrows)

**Comment by turtlewit** [comment]
The problem here is that the game looks for a word after the word 'inspect'. It does not know if there is a word after it or not, so when there isn't, the game tries to access the 2nd item in a list of 1, and then crashes. This can be fixed by adding a check for length of list. Has been fixed.
